theme: jekyll-theme-minimal
   defaults:
  -
    scope:
      path: ""
     values:
      layout: "default"
  -
    scope:
      path: "index.html"
       values:
      layout: "frontpage" # overrides previous default layout
